export {operation_ as confirmProduct} from './confirmProduct.mjs'
export {operation as getPendingProducts} from './getPendingProducts.mjs'
export {operation as getReviews} from './getReviews.mjs'
export {operation_ as rejectProduct} from './rejectProduct.mjs'
export {operation as getUser} from './getUser.mjs'
